
enum AppExceptionCode {
  CODE_000_ERROR_UNEXPECTED,
  CODE_001_CUSTOMER_LOCAL_NOT_FOUND,
  CODE_002_CUSTOMER_SERVER_NOT_FOUND,
  CODE_003_CUSTOMER_DATA_INVALID,
  CODE_004_PRODUCT_LOCAL_NOT_FOUND,
  CODE_005_PRODUCT_SERVER_NOT_FOUND,
  CODE_006_PRODUCT_DATA_INVALID,
  CODE_007_AUTH_INVALID_CREDENTIALS,   // credenciais incorretas (usuário ou senha)
  CODE_008_AUTH_ACCOUNT_LOCKED,        // conta bloqueada
  CODE_009_AUTH_ACCOUNT_INACTIVE,      // conta inativa
  CODE_010_AUTH_MFA_REQUIRED,          // é necessário MFA (autenticação de dois fatores)
  CODE_011_AUTH_MFA_FAILED,            // falha na validação do MFA
  CODE_012_AUTH_NETWORK_ERROR,         // erro de rede durante o login
  CODE_013_AUTH_TIMEOUT,               // tempo de resposta do servidor esgotado
  CODE_014_USER_NOT_FOUND,
  CODE_015_CITY_REQUIRED,
  CODE_016_STATE_REQUIRED,
  CODE_017_STREET_REQUIRED,
  CODE_018_DISTRICT_REQUIRED,
  CODE_019_TYPE_REQUIRED,
  CODE_020_CEP_REQUIRED,
  CODE_021_CEP_INVALID_LENGTH,
  CODE_022_PHONE_INVALID_LENGTH,
  CODE_023_PHONE_INVALID_DDD,
  CODE_024_PHONE_INVALID_NUMBER,
  CODE_025_CONTACT_NAME_REQUIRED,
  CODE_026_CONTACT_EMPTY,
  CODE_027_NAME_INVALID,
  CODE_028_EMAIL_INVALID,
  CODE_029_EMAIL_REQUIRED,
  CODE_030_DOCUMENT_REQUIRED,          // nem CPF nem CNPJ
  CODE_031_DOCUMENT_CONFLICT,           // CPF e CNPJ juntos
  CODE_032_PERSON_NAME_REQUIRED,        // PF sem nome
  CODE_033_CUSTOMER_ADDRESS_REQUIRED,
  CODE_034_CUSTOMER_CONTACT_REQUIRED,
  CODE_035_CUSTOMER_PAYMENT_METHOD_REQUIRED,
  CODE_036_CPF_REQUIRED,
  CODE_037_CPF_INVALID_LENGTH,
}



