// ignore_for_file: constant_identifier_names

enum AppExceptionCode {
  CODE_000_ERROR_UNEXPECTED,
  CODE_001_CUSTOMER_LOCAL_NOT_FOUND,
  CODE_002_CUSTOMER_SERVER_NOT_FOUND,
  CODE_003_CUSTOMER_DATA_INVALID,
  CODE_004_PRODUCT_LOCAL_NOT_FOUND,
  CODE_005_PRODUCT_SERVER_NOT_FOUND,
  CODE_006_PRODUCT_DATA_INVALID
}



